### ISSUE TITLE
PublicSuffix.valid? returns true for any value containing two periods

### ISSUE THREAD

**Issue by jurre** [weppos/publicsuffix-ruby#113]
Since the new PSL algorithm `PublicSuffix.valid?` returns true for any value containing two+ periods. This was previously not the case, and I'm not sure if it's expected behavior (didn't find any tests to indicate this).

```ruby
irb(main):006:0> PublicSuffix.valid?("this is not valid...")
=> true

irb(main):010:0> PublicSuffix.valid?("this is not valid.")
=> false
```

If I understand correctly I should be able to pass in a different default_rule to fix the issue in our app for now, so I'll go ahead and do that.

If this is indeed an issue and there's anything I can do to help, please let me know.

**Comment by weppos** [comment]
Validating input is something I'm always torn about. As ideally, the input you provide to the library should be already filtered and validated.

The purpose of this library is not to validate the format of a domain, rather to determine how to decompose the domain name passed as argument.

I'm saying that because there are a large number of possible invalid inputs you can pass. The string you provided, for instance, contain spaces.

I already do some kind of limited validations:
https://github.com/weppos/publicsuffix-ruby/blob/master/lib/public_suffix.rb#L165-L167
but frankly I'm not inclined to add more complexity for a validation that is beyond the scope of this library.

I'll take some time to consider if adding multiple dots. However, adding it will solve _one_ issue, but then what if
- you pass dot at the end?
- you pass a string with a space?

In this case, passing a different `default_rule` would not affect the algorithm.

**Comment by weppos** [comment]
I also have one more question for you. To better determine the extent of this issue, can I ask you how you currently use the library? What is the use case?

**Comment by jurre** [comment]
We currently use `PublicSuffix.valid?` to determine if user supplied input is a url, ip or other string. From your previous reply I understand that this is probably not the intended usage of the library, and I should probably consider a different approach.

**Comment by weppos** [comment]
Yes, correct. The purpose of this library is really not to handle URL validation.

**Comment by weppos** [comment]
FYI https://rubygems.org/gems/addressable is probably a better solution.

**Comment by jurre** [comment]
Yes, Addressable makes sense. I'll look into switching to that, we already have a dependency on it elsewhere.

Should I close this issue?

Thanks for your help!
