### ISSUE TITLE
v1.5 introduced a breaking change.

### ISSUE THREAD

**Issue by ljharb** [weppos/publicsuffix-ruby#127]
travis-ci installs `github-pages-health-check`, which depends on `~> 1.4` of `public_suffix`.

However, our ruby 1.9 builds don't work, since 1.5 incorrectly included a breaking change in a minor version.

It would be appropriate to release a 1.x release that is ruby 1.9-compatible, since it's probably way too late to unpublish all of the versions 1.5+.

**Comment by dentarg** [comment]
Seems like the change to drop support for Ruby 1.x in 1.5 was very much intentional: https://github.com/weppos/publicsuffix-ruby/blob/master/CHANGELOG.md#release-150 (https://github.com/weppos/publicsuffix-ruby/commit/e39a3d7023475da6052b83cd9f676fd6ee5b9032)

If it was incorrect to do so all depends on if this project has (or back then, had) the ambition to follow [semver](http://semver.org). I'm not sure that is (was) the case, as I can't find any mentioning (used the github repo search).

**Comment by ljharb** [comment]
The change log entry doesn't imply the decision was made intentionally to violate semver, just that the decision to drop was intentional.

Following semver is of course not a requirement, it's a choice, but conveying breakage clearly through version numbers is an important means to giving confidence to users to use and upgrade your software. It would be very unfortunate if this project chose, with all the information, not to follow semver.

**Comment by weppos** [comment]
The decision to drop Ruby 1.x was intentional. I do follow semver, but at the same time I don't believe dropping Ruby 1.x support in a mini version is a violation of semver.

There is no explicit mentioning to language versions in semver. semver mention that "API changes" should require a major version.

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

Dropping Ruby 1.9 support did not introduce any API change.

See also [What should I do if I update my own dependencies without changing the public API?](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)

> That would be considered compatible since it does not affect the public API.

For the sake of my curiosity, I talked with other Ruby gem maintainers, and all of them agreed with me that a major change was not required.

If you have specific references or evidences that changing the Ruby dependencies should have been considered a major in semver, feel free to share them.

**Comment by ljharb** [comment]
The public API includes platform and language support - in other words, it's a breaking change if any code that worked previously stops working.

The Ruby community has a history of violating semver in minor versions because they "don't think the breakage matters", so it's unfortunate to see that continue here.

**Comment by weppos** [comment]
> The public API includes platform and language support

Sadly, semver is not clear on this topic, and everything is open to interpretation.

**Comment by ljharb** [comment]
Right - then it becomes whether you think it's more important to keep the first number small, or to not break your users :-/

**Comment by weppos** [comment]
@ljharb frankly, I was confident that bundler would have been able to figured out the appropriate version to pull down, according to dependencies _and_ Ruby version.

In fact, my expectation was that _if_ you set for example `~> 1.4` and your system was using 1.9, given the gemfile contained the detail of the minimum Ruby version then bundler would have treated it as a stopped and kept you on 1.4, rather than installing 1.9.

According to your comment, it doesn't seem the case. If you have a public log of a build, I'd like to take a look at it.

**Comment by ljharb** [comment]
Sure - https://travis-ci.org/airbnb/hypernova-ruby/builds/174902780

I think it's because we're using bundler 1.7.6 - I believe a newer version might have automatically grabbed the right version of your gem. If so, a workaround certainly could be "upgrade bundler" - but the principle remains that if it worked on bundler 1.7.6 in any 1.x, it needs to work on that version of bundler in every 1.x :-/
