### ISSUE TITLE
Possible error installing when path contains a space

### ISSUE THREAD

**Issue by MoralCode** [weppos/publicsuffix-ruby#181]
I suspect there may be an issue where public_suffix is not able to be installed with bundler when the path to the project has a space in it. I have seen this issue with other jekyll dependencies and 

As an example, say I have a Jekyll site (which has dependencies that depend on public_suffix). If I clone that site to `C:\Users\My Username\Desktop\Site` the installation will fail with the message 
`Errno::EACCES: permission denied @ rb_sysopen - C:/Users/My Username/Desktop/Site/vendor/bundle/ruby/2.7.0/gems/public_suffix-4.0.5/LICENSE.txt`

I havent collected enough info yet to be sure that this is the cause, but wanted to report this as soon as possible just in case it helps other people.

**Comment by weppos** [comment]
Thanks for reporting the issue. Unfortunately, this is not something specific to this gem, as you also pointed out. It is related to your system configuration and/or RubyGems.

From what I can see, the process that run the script was not able to write on the Site folder on your desktop due to missing permission.
