### ISSUE TITLE
Handling IDN/Punycode

### ISSUE THREAD

**Issue by gdlx** [weppos/publicsuffix-ruby#24]
Hi, 

It would be nice to add IDN/Punycode encoding to PublicSuffix.

I'm currently using `simpleidn` to do the job but it would make sense to have everything inside a single class.

I'll try to send a pull request when I'll have some time for this but maybe you already have plans on this subject.

Thanks anyway for this great gem !

**Comment by dentarg** [comment]
> it would be better to have another gem, that depends on PublicSuffix and SimpleIDN, providing a "full perimeter" domain management class

@gauthier-delacroix some years later, but if you still want this, https://github.com/twingly/twingly-url does this... :) (but using [addressable](https://github.com/sporkmonger/addressable) instead of simpleidn)

at https://github.com/twingly/twingly-url/blob/v5.0.1/lib/twingly/public_suffix_list.rb we extend the PSL with the punycoded versions
