### ISSUE TITLE
Expected behavior for rule exceptions

### ISSUE THREAD

**Issue by benbalter** [weppos/publicsuffix-ruby#63]
For [Gman](https://github.com/benbalter/gman) I use a custom public suffix-formatted list, and would like to add an exception. I'm not sure if the current rule exception behavior works as intended, or if I'm just not understanding it properly:

On the public suffix list, I see an entry `!city.kobe.jp`, but can't seem to get any indication of the exception:

```irb
[14] pry(main)> PublicSuffix.valid? "city.kobe.jp"
=> true
[15] pry(main)> PublicSuffix.valid? "foo.city.kobe.jp"
=> true
[16] pry(main)> PublicSuffix.valid? "foo.bar.city.kobe.jp"
=> true
```

In my own implementation, when I call find on an excepted domain, it returns the Exception as expected, but `rule.allow?` still passes the domain (the check that `valid?` uses).

Am I missing something?

**Comment by weppos** [comment]
Hi @benbalter, in the [Public Suffix specifications](https://publicsuffix.org/list/) and exception is considered as

> An exclamation mark (!) at the start of a rule marks an exception to a previous wildcard rule. An exception rule takes priority over any other matching rule.

In other words, it is not expected to raise any explicit exception, the exception is just supposed to override a previous wildcard rule.

That's why you get

```
PublicSuffix.valid? "city.kobe.jp"
=> true
```

Without that specific exception, the rule `city.kobe.jp` would not be valid as there is a wildcard rule that denies it. For instance

```
2.1.5 :002 > PublicSuffix.valid? "foo.kobe.jp"
 => false
```

If you add the `!foo.kobe.jp` exception, then `foo.kobe.jp` becomes a valid suffix.

Does it make sense for you? I believe you intended the exception as a specific blacklist of a rule, whereas is exactly the opposite, it's a specific whitelist that overrides a wildcard blacklist.

**Comment by benbalter** [comment]
Ahh. That makes sense. Thanks for the clarification and for a great :gem:. Using it heavily on GitHub.com, if it's not apparent from the context. :smile:

**Comment by weppos** [comment]
@benbalter I know you guys used this and the [whois](https://github.com/weppos/) in the past, I'm glad about it. Thanks for your feedback! :+1:
